# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Install Qt
      id: qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        # Directory to install Qt
        dir: '${{ github.workspace }}'
        # Version of Qt to install
        version: '5.13.2'
        # Host platform
        host: 'windows'
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: 'win64_mingw73'
        # Whether or not to install Qt dependencies on Linux
        install-deps: true
        # Additional Qt modules to install
        modules: ''
        # Force a Qt mirror in case the default is not working
        mirror: ''
        # Whether or not to actually download Qt
        cached: false
        # Version of aqtinstall to use in case of issues
        aqtversion: '==0.9.4'
        # Version of py7zr to use in case of issues
        py7zrversion: '==0.9.1'
        # Any extra arguments to append to the back
        extra: '--external 7z'

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build
      run: |
        set PATH=$ENV{Qt5_DIR}\bin;$ENV{Qt5_DIR}\..\..\Tools\mingw73_64/bin;%PATH%
        cd ${{ github.workspace }}
        qmake
        mingw64-make.exe
